### PR TITLE
feat: Include enum name into enum details object

### PR DESCRIPTION
**Pull request by Grandlouis**

### CODE REVIEW

**Comment by stephenh** [comment]
This looks great; can you run "yarn codegen" to update the generated code, and include that in the PR?

**Comment by Grandlouis** [comment]
> This looks great; can you run "yarn codegen" to update the generated code, and include that in the PR?

Sure, pushing update 👍

**Comment by stephenh** [comment]
@Grandlouis feel free to hit merge once the tests pass; that will auto-release a new version to npm that you can pull into graphql-service. Thanks!

**Pull request merged**
