### PR TITLE
feat: detag ids with config

### PR DESCRIPTION
**Pull request by mmahalwy**

### CODE REVIEW

**Comment by mmahalwy** [comment]
wip but looking for initial feedback

**Review by stephenh — APPROVED** [review]

**Comment by stephenh** [comment]
@mmahalwy this looks like a good start! Going to merge and see how it goes.

Fwiw for `id` --> `taggedId` fixes going forward, would like to have regression tests for as much of those as possible in the `untagged-ids` project otherwise I'm almost certain we'll have regression as we tweak/refactor our id approach going forward (i.e. to support numbers).

I thought a little bit about "should we duplicate the _entire_ / existing integration-tests suite"? Which I don't think is the right answer, so I think for now just copy/pasting/re-creating a subset of tests that we know are actually needed to coverage untagged id behavior seems like the most pragmatic / albeit tedious approach.

I'm also flip-flopping on the name `taggedId` --> `idTagged`, b/c we had an existing `idUntagged`, and so `idTagged` lines up with that. So I went ahead and pushed that to the PR before merging...

So :shrug: I guess try this out and let us know how it goes. Thanks!

**Comment by mmahalwy** [comment]
thanks @stephenh for bringing this across the finish line!

**Pull request merged**
