### PR TITLE
docs: Add `tsvector` full text search example

### PR DESCRIPTION
**Pull request by blambillotte**

### CODE REVIEW

**Comment by blambillotte** [comment]
@stephenh Took a stab at an example of full text search. I couldn't quite figure out where to put it, maybe it makes senes to make a new `Examples` top level folder? `Getting Started/Examples` isn't quite right.

**Comment by stephenh** [comment]
@blambillotte this looks great!

In terms of where to put it :thinking: , yeah, seems like maybe we eventually need like a "Recipes" or "Examples" dedicated section.

But for now given we have only one example, it seems overkill to create a new section quite yet.

Wdyt of just putting it into the "Advanced Features" section for now?

**Review by stephenh — APPROVED** [review]
:100:

**Pull request merged**
